In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
train=pd.read_csv("train_df_errno.csv")
test=pd.read_csv("test_df.csv")

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2896 entries, 0 to 2895
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   단지코드        2896 non-null   object 
 1   총세대수        2896 non-null   int64  
 2   임대건물구분      2896 non-null   object 
 3   지역          2896 non-null   object 
 4   공급유형        2896 non-null   object 
 5   전용면적        2896 non-null   float64
 6   전용면적별세대수    2896 non-null   int64  
 7   공가수         2896 non-null   float64
 8   자격유형        2896 non-null   object 
 9   임대보증금       2327 non-null   object 
 10  임대료         2327 non-null   object 
 11  10분내지하철수    2685 non-null   float64
 12  10분내버스정류장수  2892 non-null   float64
 13  단지내주차면수     2896 non-null   float64
 14  등록차량수       2896 non-null   float64
dtypes: float64(6), int64(2), object(7)
memory usage: 339.5+ KB


In [5]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   단지코드        1008 non-null   object 
 1   총세대수        1008 non-null   int64  
 2   임대건물구분      1008 non-null   object 
 3   지역          1008 non-null   object 
 4   공급유형        1008 non-null   object 
 5   전용면적        1008 non-null   float64
 6   전용면적별세대수    1008 non-null   int64  
 7   공가수         1008 non-null   float64
 8   자격유형        1006 non-null   object 
 9   임대보증금       828 non-null    object 
 10  임대료         828 non-null    object 
 11  10분내지하철수    970 non-null    float64
 12  10분내버스정류장수  1008 non-null   float64
 13  단지내주차면수     1008 non-null   float64
dtypes: float64(5), int64(2), object(7)
memory usage: 110.4+ KB


In [6]:
train.shape, test.shape

((2896, 15), (1008, 14))

In [7]:
sel = ['총세대수','전용면적별세대수','전용면적','공가수','단지내주차면수']

X = train[sel]
y = train['등록차량수']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=42)

In [8]:
from sklearn.linear_model import LinearRegression

In [10]:
model = LinearRegression()
model.fit(X_train, y_train)   # 학습
pred = model.predict(X_test)
pred

array([ 782.32608196, 1635.92038674,  406.51136874,  445.84012422,
        744.68661201,  552.2994118 ,  325.22215812, 1388.19432823,
        759.44374212,   98.87936989,  267.93232237,  721.57384767,
        955.75855777, 1128.70747172,  273.83863706,  476.15298623,
       1183.7122787 ,  367.62467013,  701.05170052,  570.34445029,
        327.69706643,  484.09083548,  746.01962672,  466.19250036,
        447.19652096,  558.47303296,  552.2994118 ,  550.00061552,
        -47.66281847,  327.13687855,  264.57074071,  301.16525285,
        627.46315129,  254.15266815,  570.13596572,  572.27168422,
        511.67733804,  387.98040517,  834.86062103,  594.81547891,
        545.72528292,   71.42819998,  735.11746492, 1678.79916214,
        704.13264111,  461.66071315,  817.52951968,  325.48171011,
        396.24056348,  312.92363862,  552.00740238,  698.56539548,
        922.95781568,  -15.78191046,  697.0748257 ,    4.95402566,
       1029.19397991,  456.97474779,  694.58139401,  387.62727

In [16]:
dict_dat = {"실제값 " : y_test, "예측값" : pred, "오차절대값" :abs( y_test - pred),
           "오차제곱" : (y_test - pred)**2}
dat = pd.DataFrame(dict_dat)
dat

실제값           예측값       오차절대값           오차제곱
141    671.0   782.326082  111.326082   12393.496525
2476  2550.0  1635.920387  914.079613  835541.539385
1750   509.0   406.511369  102.488631   10503.919537
1709   528.0   445.840124   82.159876    6750.245188
1925   614.0   744.686612  130.686612   17078.990558
...      ...          ...         ...            ...
1873  1350.0  1686.816798  336.816798  113445.555210
2564   701.0   871.524937  170.524937   29078.754188
1543   417.0   485.373565   68.373565    4674.944375
2384   526.0   484.796869   41.203131    1697.698015
2804  1374.0  1287.951101   86.048899    7404.412981

[869 rows x 4 columns]

In [17]:
###학습 데이터 셋의 결정계수
print('학습 데이터 셋:',model.score(X_train,y_train))
print('테스트 데이터 셋:',model.score(X_test,y_test))

학습 데이터 셋: 0.7914535320120472
테스트 데이터 셋: 0.7693803206856491


### MAE

In [18]:
sum(dat['오차절대값'])/len(dat['오차절대값'])

149.69137512052592

### MSE

In [20]:
mse_val = sum(dat['오차제곱']) / len(dat['오차제곱'])
mse_val

45240.34947834261

### RMSE 

In [22]:
rmse = np.sqrt(mse_val)
rmse

212.69778907723185

### LASSO    

In [23]:
from sklearn.linear_model import Lasso, Ridge # Lasso : L1, Ridge: L2
lasso = Lasso(alpha=0.01).fit(X_train, y_train)
print("학습용 데이터 세트 점수 : {:.2f}".format(lasso.score(X_train, y_train)))
print("테스트 데이터 세트 점수 : {:.2f}".format(lasso.score(X_test, y_test)))

학습용 데이터 세트 점수 : 0.79
테스트 데이터 세트 점수 : 0.77


### LIDGE

In [24]:
from sklearn.linear_model import Lasso, Ridge # Lasso : L1, Ridge: L2
ridge = Ridge(alpha=0.1).fit(X_train, y_train)
print("학습용 데이터 세트 점수 : {:.2f}".format(ridge.score(X_train, y_train)))
print("테스트 데이터 세트 점수 : {:.2f}".format(ridge.score(X_test, y_test)))

학습용 데이터 세트 점수 : 0.79
테스트 데이터 세트 점수 : 0.77


In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

###  LASSO모델 적용해보기. MAE, MSE 구해보기

In [46]:
sel = [0.0, 0.1, 0.2, 0.01, 0.3 ] #0.0001이 가장크다.
for var in sel:
    lasso = Lasso(alpha=var)
    lasso.fit(X_train, y_train)
    pred = lasso.predict(X_test)
    MAE = mean_absolute_error(y_test, pred)
    MSE = mean_squared_error(y_test, pred)
    print('alpha:{}'.format(var))
    print("학습용 데이터 세트 점수 : {:.3f}".format(lasso.score(X_train, y_train)))
    print("테스트 데이터 세트 점수 : {:.3f}".format(lasso.score(X_test, y_test)))
    print('MSE:{}'.format(MSE))
    print('MAE:{}'.format(MAE))
    print()

alpha:0.0
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.34947834261
MAE:149.6913751205259

alpha:0.1
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.7103567406
MAE:149.69036501063047

alpha:0.2
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45241.07146714965
MAE:149.68935481144564

alpha:0.01
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.38555641543
MAE:149.69127410733753

alpha:0.3
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45241.43277903844
MAE:149.68834480421455



<ipython-input-46-91b9a542531a>:4: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  lasso.fit(X_train, y_train)
C:\Users\chlal\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
C:\Users\chlal\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 39875948.412371576, tolerance: 38241.78735520474
  model = cd_fast.enet_coordinate_descent(


### LIDGE모델 적용해보기. MAE, MSE 구해보기

In [45]:
sel = [0.0, 0.1, 0.2, 0.01, 0.3 ] #0.0001이 가장크다.
for var in sel:
    ridge = Ridge(alpha=var)
    ridge.fit(X_train, y_train)
    pred = ridge.predict(X_test)
    MAE = mean_absolute_error(y_test, pred)
    MSE = mean_squared_error(y_test, pred)
    print('alpha:{}'.format(var))
    print("학습용 데이터 세트 점수 : {:.3f}".format(ridge.score(X_train, y_train)))
    print("테스트 데이터 세트 점수 : {:.3f}".format(ridge.score(X_test, y_test)))
    print('MSE:{}'.format(MSE))
    print('MAE:{}'.format(MAE))
    print()

alpha:0.0
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.3494783426
MAE:149.6913751205259

alpha:0.1
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.35043271786
MAE:149.69137244555353

alpha:0.2
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.35138709382
MAE:149.69136977058375

alpha:0.01
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.349573780084
MAE:149.69137485302858

alpha:0.3
학습용 데이터 세트 점수 : 0.791
테스트 데이터 세트 점수 : 0.769
MSE:45240.352341470505
MAE:149.69136709561656



###  데이터 전처리 등을 한 이후에 MAE, MSE 모델 적용.

* 결측치 처리

In [47]:
train.columns = ['단지코드', '총세대수', '임대건물구분', '지역', '공급유형', '전용면적', '전용면적별세대수', '공가수',
       '자격유형', '임대보증금', '임대료', '10분내지하철수',
       '10분내버스정류장수', '단지내주차면수', '등록차량수']
test.columns = ['단지코드', '총세대수', '임대건물구분', '지역', '공급유형', '전용면적', '전용면적별세대수', '공가수',
       '자격유형', '임대보증금', '임대료', '10분내지하철수',
       '10분내버스정류장수', '단지내주차면수']

In [48]:
train.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         569
임대료           569
10분내지하철수      211
10분내버스정류장수      4
단지내주차면수         0
등록차량수           0
dtype: int64

In [49]:
test.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            2
임대보증금         180
임대료           180
10분내지하철수       38
10분내버스정류장수      0
단지내주차면수         0
dtype: int64

### 자격유형 결측치 처리

In [50]:
test.loc[196,'자격유형']='A'
test.loc[258,'자격유형']='C'

In [51]:
test.loc[[196,258],:]

단지코드  총세대수 임대건물구분    지역  공급유형   전용면적  전용면적별세대수   공가수 자격유형     임대보증금  \
196  C2411   962    아파트  경상남도  국민임대  46.90       240  25.0    A  71950000   
258  C2253  1161    아파트   강원도  영구임대  26.37       745   0.0    C   2249000   

       임대료  10분내지하철수  10분내버스정류장수  단지내주차면수  
196  37470       0.0         2.0    840.0  
258  44770       0.0         2.0    173.0

In [52]:
print(train.자격유형.unique())
print(test.자격유형.unique())

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O']
['H' 'A' 'E' 'C' 'D' 'G' 'I' 'J' 'K' 'L' 'M' 'N']


In [53]:
mapping = { 'A':1, 'B':2, 'C':3, 'D':4, 'E':5,
            'F':6, 'G':7, 'H':8, 'I':9, 'J':10,
            'K':11, 'L':12, 'M':13, 'N':14, 'O':15  }
train['자격유형'] =train['자격유형'].map(mapping).astype(int)
test['자격유형'] =test['자격유형'].map(mapping).astype(int)

In [54]:
print(train.자격유형.unique())
print(test.자격유형.unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 8  1  5  3  4  7  9 10 11 12 13 14]


In [55]:
train.head()

단지코드  총세대수 임대건물구분    지역  공급유형   전용면적  전용면적별세대수   공가수  자격유형     임대보증금  \
0  C2515   545    아파트  경상남도  국민임대  33.48       276  17.0     1   9216000   
1  C2515   545    아파트  경상남도  국민임대  39.60        60  17.0     1  12672000   
2  C2515   545    아파트  경상남도  국민임대  39.60        20  17.0     1  12672000   
3  C2515   545    아파트  경상남도  국민임대  46.90        38  17.0     1  18433000   
4  C2515   545    아파트  경상남도  국민임대  46.90        19  17.0     1  18433000   

      임대료  10분내지하철수  10분내버스정류장수  단지내주차면수  등록차량수  
0   82940       0.0         3.0    624.0  205.0  
1  107130       0.0         3.0    624.0  205.0  
2  107130       0.0         3.0    624.0  205.0  
3  149760       0.0         3.0    624.0  205.0  
4  149760       0.0         3.0    624.0  205.0

In [57]:
train.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         569
임대료           569
10분내지하철수      211
10분내버스정류장수      4
단지내주차면수         0
등록차량수           0
dtype: int64

### 10분내버스정류장수 결측치 처리

In [62]:
train['10분내버스정류장수'].unique()

array([ 3.,  1.,  2.,  6., 10.,  5.,  4.,  7., 12., 14.,  8.,  0., 20.,
       11., 16., 15., nan, 19.])

In [63]:
print(train['10분내버스정류장수'].value_counts())

2.0     776
3.0     737
4.0     485
1.0     270
5.0     162
6.0     153
8.0      99
10.0     80
7.0      65
12.0     22
20.0     15
15.0     11
16.0      6
19.0      4
11.0      3
14.0      2
0.0       2
Name: 10분내버스정류장수, dtype: int64


* 결측치를 2.0으로 채워줌

In [64]:
#결측치 처리
train['10분내버스정류장수'] = train['10분내버스정류장수'].fillna(2.0)

In [65]:
train.isnull().sum()

단지코드            0
총세대수            0
임대건물구분          0
지역              0
공급유형            0
전용면적            0
전용면적별세대수        0
공가수             0
자격유형            0
임대보증금         569
임대료           569
10분내지하철수      211
10분내버스정류장수      0
단지내주차면수         0
등록차량수           0
dtype: int64

In [66]:
train['10분내버스정류장수'].unique()

array([ 3.,  1.,  2.,  6., 10.,  5.,  4.,  7., 12., 14.,  8.,  0., 20.,
       11., 16., 15., 19.])

### 10분내지하철수

In [83]:
train['10분내지하철수'].unique()

array([ 0.,  1., nan,  2.,  3.])

In [84]:
print(train['10분내지하철수'].value_counts())

0.0    2246
1.0     400
2.0      33
3.0       6
Name: 10분내지하철수, dtype: int64


In [85]:
#결측치 처리
train['10분내지하철수'] = train['10분내지하철수'].fillna(0.0)

In [86]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2896 entries, 0 to 2895
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   단지코드        2896 non-null   object 
 1   총세대수        2896 non-null   int64  
 2   임대건물구분      2896 non-null   object 
 3   지역          2896 non-null   object 
 4   공급유형        2896 non-null   object 
 5   전용면적        2896 non-null   float64
 6   전용면적별세대수    2896 non-null   int64  
 7   공가수         2896 non-null   float64
 8   자격유형        2896 non-null   int32  
 9   임대보증금       2327 non-null   object 
 10  임대료         2327 non-null   object 
 11  10분내지하철수    2896 non-null   float64
 12  10분내버스정류장수  2896 non-null   float64
 13  단지내주차면수     2896 non-null   float64
 14  등록차량수       2896 non-null   float64
dtypes: float64(6), int32(1), int64(2), object(6)
memory usage: 328.2+ KB


In [87]:
sel = ['총세대수','자격유형','10분내버스정류장수','전용면적별세대수','10분내지하철수']

X = train[sel]
y = train['등록차량수']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=42)

In [88]:
model = LinearRegression()
model.fit(X_train, y_train)   # 학습
pred = model.predict(X_test)
pred

array([ 947.49991562, 1299.12223377,  459.04071403,  502.50167715,
        608.35469513,  982.13252776,  535.93643284,  852.68136453,
        620.9069518 ,  520.52584668,  437.82399179,  556.88118183,
        721.90116804, 1052.67210169,  261.30809496,  466.89834804,
        667.20675484,  461.55240166,  608.44295486,  726.55785357,
        431.13941052,  402.22010109,  239.78966375,  499.38987787,
        519.92268677,  508.73865122,  982.13252776,  419.08702059,
        606.41259353,  437.48398155,  629.45141554,  110.96846497,
        294.4012839 ,  384.3024341 ,  610.47119348,  443.06672515,
        533.29244099,  456.38467564,  887.45990147,  427.02309898,
        363.4218311 ,  324.78433948,  560.85851264,  843.33436618,
        571.7919069 ,  540.60893465,  655.7270474 ,  293.18892126,
        384.3962924 ,  258.20972068,  547.59118256,  391.40164036,
        562.02639255,  474.89111084,  370.49642882,  886.04415238,
        729.60888402,  423.89883619,  615.47345048,  548.36017

In [89]:
dict_dat = {"실제값 " : y_test, "예측값" : pred, "오차절대값" :abs( y_test - pred),
           "오차제곱" : (y_test - pred)**2}
dat = pd.DataFrame(dict_dat)
dat

실제값           예측값        오차절대값          오차제곱
141    671.0   947.499916   276.499916  7.645220e+04
2476  2550.0  1299.122234  1250.877766  1.564695e+06
1750   509.0   459.040714    49.959286  2.495930e+03
1709   528.0   502.501677    25.498323  6.501645e+02
1925   614.0   608.354695     5.645305  3.186947e+01
...      ...          ...          ...           ...
1873  1350.0   824.751956   525.248044  2.758855e+05
2564   701.0   679.049816    21.950184  4.818106e+02
1543   417.0   525.563810   108.563810  1.178610e+04
2384   526.0   466.898348    59.101652  3.493005e+03
2804  1374.0   768.772532   605.227468  3.663003e+05

[869 rows x 4 columns]

### MAE

In [90]:
sum(dat['오차절대값'])/len(dat['오차절대값'])

293.00382447967735

### MSE

In [91]:
mse_val = sum(dat['오차제곱']) / len(dat['오차제곱'])
mse_val

157339.8528342326

### RMSE

In [92]:
rmse = np.sqrt(mse_val)
rmse

396.6608788804772